name: cran-status-checks.yaml
#Check CRAN status periodically

on:
  schedule:
    # Runs daily at 4:00 PM UTC (9:00 AM PST)
    - cron: '0 9 * * *'  
  # allows for manually running of the check
  workflow_dispatch:

jobs:
  check_cran_status:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::urlchecker, any::yyjsonr
          
      - name: URL check
        run: |
          urls_checks <- urlchecker::url_check()
          if(nrow(urls_checks)>0){
            stop(print(urls_checks))
          }else{
            print(urls_checks)
          }
        shell: Rscript {0}
        
      - name: Check CRAN-checks status
          # from https://github.com/ricochet-rs/cran-checks/blob/main/check-pkg/action.yaml
        id: cran-check-status
        run: |
          pkg <- "cytometree"
          fp <- paste0("https://ricochet-rs.github.io/cran-checks/", pkg, ".json")

          json <- tryCatch(readLines(fp),
            warning = function(e) {
              stop("Package ", pkg, " not found in CRAN checks", call. = FALSE)
            }
          )

          res <- yyjsonr::read_json_str(json)
          
          if (any("ERROR" %in% res$results[[1]]$check_status)) {
            stop(
              "Errors found in CRAN checks",
              "\n",
              "Review logs at ", 
              "https://cran.r-project.org/web/checks/check_results_", pkg, ".html"
            )
          } else if (any(grepl("WARN", res$results[[1]]$check_status))) {
            stop(
              "Warnings found in CRAN checks",
              "\n",
              "Review logs at ", 
              "https://cran.r-project.org/web/checks/check_results_", pkg, ".html"
            )
          } else if (!is.data.frame(res$issues)) {
            issues <- res$issues[[1]]
            stop(
              "Additional issues detected:\n",
              sprintf("  - %s: %s\n", issues$kind, issues$href)
            )
          } else if (any(grepl("NOTE", res$results[[1]]$check_status))) {
            stop(
              "NOTES found in CRAN checks",
              "\n",
              "Review logs at ", 
              "https://cran.r-project.org/web/checks/check_results_", pkg, ".html"
            )
          }
          message("\u2713 `", pkg, "` has no notes, issues, warnings or errors")
        shell: Rscript {0}
      
